apiVersion: v1
appVersion: v0.30.1
description: Prometheus SNMP Exporter
home: https://github.com/prometheus/snmp_exporter
keywords:
- prometheus
- snmp
- monitoring
maintainers:
- email: github@xiu.io
  name: xiu
  url: https://github.com/xiu
- email: walker.thomas.p@gmail.com
  name: walker-tom
  url: https://github.com/walker-tom
name: prometheus-snmp-exporter
sources:
- https://github.com/prometheus/snmp_exporter
version: 9.13.1
