apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network-observability

labels:
  - pairs:
      app.kubernetes.io/part-of: network-observability
    includeSelectors: false

resources:
  - common
  - infra-telemetry
  - flow-analytics
  - k8s-visibility
  - alerting
